name: Check code

on:
  pull_request:
    branches:
      - main

jobs:
  check-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check Prisma Migrations
        uses: premieroctet/prisma-drop-migration-warning@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          main-branch: 'main'
          path: 'prisma'
          warning: true